### ISSUE TITLE
option selected="selected" attribute does not update

### ISSUE THREAD

**Issue by joshvito** [leocaseiro/angular-chosen#130] opened 2015-08-12 17:01 UTC
Why doesn't the selected `<option>` element get updated with the "selected='selected' " attribute?

![selected_is_not_selected](https://cloud.githubusercontent.com/assets/1249866/9230721/ea6ec194-40f1-11e5-9229-853fe74eef46.jpg)

**Comment by joshvito** [comment] 2015-08-12 17:24
It appears the property of the option is updated to selected:true, where the attrubute does not update, it is used for initial load.

**Comment by leocaseiro** [comment] 2016-03-10 12:35
Duplicate of #58

**Closed by leocaseiro** 2016-03-10 12:35 UTC
