### ISSUE TITLE
Getting blank selection when using inside the ui grid in IE11

### ISSUE THREAD

**Issue by santhanapaul** [leocaseiro/angular-chosen#241] opened 2017-06-08 13:07 UTC
Hi,

I am getting blank selection when using angular-chosen inside the ui grid template in IE11. Please guide me to fix this.
ui grid columndef:
```js
{ name: 'value', displayName: "Value", minWidth: 180, cellTemplate: 'app/search/value-cell.html' }
```
and in html:
```html
<div class="input-group">                
	<select class="form-control" chosen multiple width="'100%'" allow-single-deselect="true"
		placeholder-text-single="Choose Options"
		no-results-text="'Data not available'" ng-model="MODEL_COL_FIELD"
		ng-options="data.label as data.label for data in grid.appScope.datas"
		name="jobcode" id="jobcode"
		class="form-control">
		<option value=""></option>
	</select>
</div>
```

**Comment by leocaseiro** [comment] 2017-06-08 23:54
Does it work outside ui grid?

**Comment by santhanapaul** [comment] 2017-06-09 04:38
when using outside of ui grid we are facing hard scrolling issue (for multiselect).

**Comment by leocaseiro** [comment] 2017-06-09 04:43
Hi @santhanapaul, I can't reproduce your issue. Is not clear what is your problem.

Could you please show me an [example](https://plnkr.co/edit/vaRw1x?p=preview) or describe exactly what the issue is?

Thanks.

**Comment by santhanapaul** [comment] 2017-06-09 05:22
@leocaseiro thanks for waiting

updated plunkr https://plnkr.co/edit/IfR0Xin5uCIoehozictI?p=preview

**Comment by leocaseiro** [comment] 2017-06-09 06:05
Hi @santhanapaul, thanks for sending me the plunker.

So the issue is only on IE11?

Unfortunately, I'm on Mac and I can't reproduce at the moment. (need to check on windows)

Have you tried if happens the same issue with jQuery without Angular? I meant, could be an issue with Chosen by itself.

Also, does it work on Edge? 
If you have any chances, could you please send me a print or a gif with the issue?
You can use http://recordit.co/ if you don't mind.

Either way, I'll try to check on Windows this long weekend(Australia).

Thanks.

**Comment by leocaseiro** [comment] 2017-06-09 06:07
PS: I've noticed some CSS here, 

```css
.chosen-container .chosen-choices {
    overflow:visible;
    max-height: 54px;
    overflow-y: auto;
}
```

Does it work without these custom styles?

**Comment by leocaseiro** [comment] 2017-06-09 06:15
Hi @santhanapaul, I've tested on my VM Ware.

I remove the CSS styles and it look nice for me:

http://recordit.co/cyeynKnZTP
or
http://g.recordit.co/cyeynKnZTP.gif

PS: Sorry for my stupid shortcuts that redimensioned the window...while I was trying to remove the style...

**Comment by santhanapaul** [comment] 2017-06-09 06:19
Maximum height to be set for that control, otherwise screen design will be collapsed. But in your shared video, height of the control dynamically increased based on no of item selection.

**Comment by leocaseiro** [comment] 2017-06-09 06:26
Yep, it should work the same way for you. Can you try on plunker?

If you need to set max-height on your multiple select chosen, what are your expecting behaviour? It should show a scroll, right?
Otherwise, I don't understand how the user can read/remove older options.

That's the same way normal multiple select works, right?

**Comment by leocaseiro** [comment] 2017-06-09 06:28
@santhanapaul I just found this old issue https://github.com/leocaseiro/angular-chosen/issues/129

**Comment by santhanapaul** [comment] 2017-06-09 06:36
@leocaseiro Yes i need scroll option, if user want to read/remove older options means they will go for scrolling. In my scenario user not able to read the older options because of the scrolling issue in IE11

**Comment by leocaseiro** [comment] 2017-06-09 07:25
Hi @santhanapaul, I believe you can try with `overflow-x: scroll` instead of visible, like so:

https://plnkr.co/edit/SiockV4hdpsxYVqkGNmt?p=preview

Hope that will do.

**Comment by santhanapaul** [comment] 2017-06-09 07:36
Hi @leocaseiro replacing overflow-x: scroll instead of visible working, but scrolling issue still persist

Hope you checking that one..

**Comment by leocaseiro** [comment] 2017-06-09 13:14
Sorry @santhanapaul, I'm not sure what's the issue.

Please, show me a screenshot or something. As I showed to you, it looks good.

**Comment by santhanapaul** [comment] 2017-06-12 06:54
Hi @leocaseiro i have shared below for the chrome and IE11 behaviour

IE: http://recordit.co/NjFJQU4Cop
Chrome: http://recordit.co/Y7FVQBNhTb

**Comment by leocaseiro** [comment] 2017-06-13 01:33
Hi @santhanapaul,

I can see there's an issue because of the auto-focus while you scroll. However, if you use the scroll from your mouse or hold the button, it works better.

There's no much I can do as this is actually a jquery-chosen issue. You might want to open an issue in their repo: https://github.com/harvesthq/chosen

Example without angular: https://plnkr.co/edit/m1pSoC?p=preview

**Comment by leocaseiro** [comment] 2017-07-06 00:20
I'm closing this issue in regards the responsibility is of chosen lib itself.

**Closed by leocaseiro** 2017-07-06 00:20 UTC
Labels: bug, chosen issue
