### ISSUE TITLE
Angular Chosem don't work well with ng-show

### ISSUE THREAD

**Issue by karimfikry** [leocaseiro/angular-chosen#84] opened 2014-10-24 02:39 UTC
I'm using chosen-angular in my project and the home page is having dropdown menu which appears after selecting some value from checkbox values. I'm ng-show to show or hide the dropdown menu. The mentioned menu don't appear well as viewed in the attached image.

![selection_036](https://cloud.githubusercontent.com/assets/1756624/4764522/0428b218-5b27-11e4-9513-ee1dc1422b12.png)

Any idea?

**Comment by Linell** [comment] 2015-01-05 19:44
Does the list display correctly if you remove the ng-show?

**Comment by karimfikry** [comment] 2015-01-05 19:46
Yes, It works well when it's used as it is. The issue happens when It was hidden and the $scope.var which show it turned to 'true' then it been viewed as shown in the attached screenshot

**Comment by Linell** [comment] 2015-01-05 19:50
Ah, I see. My select ~~is~~ was doing something similar *(I thought it'd be related to #97)*. 

I just confirmed that the problem was actually related to this one. I had everything inside of a [angular-ui tabset](http://angular-ui.github.io/bootstrap/). Removing it from that makes it work correctly for me.

**Comment by lpsBetty** [comment] 2015-01-29 17:31
What if you use 'ng-if' ?

**Comment by yfilipov** [comment] 2015-03-10 14:34
For some reason it's adding an inline style `width: 0px;`. Since I don't have the time to analyze chosen's code, I managed to fix it by setting `width: 100% !important;` (or whatever value you would need) on `.chosen-container` in chosen.css. I know it's a dirty hack, but after banging my head all day long, it works for me.

**Comment by mindmelting** [comment] 2015-05-22 09:31
I can confirm that this works correctly when using `ng-if`

**Comment by rodriguezrs** [comment] 2015-11-18 22:08
@yfilipov I removed the line in the angular-chosen.min.js that set width: 0px.  It has had no residual effects and the error described went away.

I did notice that when initializing chosen on a select when it (or its parent) is hidden causes problems.  I've got around that by explicitly setting the width of the original select in a css file or on the element itself.

**Comment by leocaseiro** [comment] 2016-03-01 21:34
Sorry the delay, I've just taken this project that was abandoned (read #162).

Hi @karimfikry would `ng-if` work for you? Could you please make a plunkr with your issue so I can manage to debug? You can use this one as an example: http://plnkr.co/edit/1U8KCH?p=preview

Thanks

**Comment by leocaseiro** [comment] 2016-03-09 11:21
The documentation is up to date to [force the use of `ng-if` instead of `ng-show`](http://leocaseiro.github.io/angular-chosen/#ng-if-instead-of-ng-show-ng-hide-example).

With that said, I'll close this issue.

**Closed by leocaseiro** 2016-03-09 11:21 UTC
Labels: bug
